GoormFintechDev1/frontend

- Dockerfile
- docker-compose.yml
- next.config.ts
- nginx/Dockerfile
- nginx/default.conf
- 작업 번호: 172973856-F-GH
- docker 설정 파일 추가, nginx 폴더 및 설정 파일 추가
> Chore(docker): docker 설정 파일 추가, nginx 폴더 및 설정 파일 추가

- package-lock.json
- package.json
- 작업 번호: 172973304-F-HJ
- 버전 수정
> Chore(package):버전다운그레이드&의존성설치

- src/app/globals.css
- src/components/Navbar.tsx
- src/components/NavbarBtn.tsx
- 작업 번호: 172983504-F-GH
- Navbar의 html, css 작성
- 현재 페이지 경로에 맞춰 bg 색상 변동
- 각 버튼 컴포넌트화 (NavbarBtn)
> Refactor(Navbar): 기능 구현

- Docker/Dockerfile
- Dockerfile
- next.config.js
- src/app/page.tsx
- src/app/register/page.tsx
- src/components/AdderssInput.tsx
- src/components/Register1.tsx
- src/components/Register2.tsx
- src/hooks/useAuthQuery.tsx
- 작업 번호: 173017230-F-HJ
- 도커 파일 추가
> Chore(dockerfile): 도커 파일 dev 모드로 추가

- src/app/page.tsx
- src/components/Login.tsx
- src/components/Register2.tsx
- src/hooks/useAuthQuery.tsx
- src/lib/authApi.ts
- 작업 번호: 173017938-F-SJ
- api 연결
> feat:login api연결

- src/app/post/page.tsx
- src/hooks/usePostsQuery.tsx
- 작업 번호: 173010528-F-GH
- infinite scrolling 테스트 페이지 추가 (post/page.tsx)
- usePostsQuery.tsx 에 infinite scrolling 관련 react-query 코드 추가 (useUsers)
> Feat(post): 무한 스크롤 테스트 페이지 제작 (/post) 에서 확인 가능

- src/app/page.tsx
- 작업 번호: 173086074-F-GH
- 메인 import 대소문자 오타 수정 profit -> Profit
> Style(main): import 대소문자 수정 profit -> Profit

- src/app/expenses/loading.tsx
- src/app/expenses/page.tsx
- src/app/page.tsx
- src/components/Loading.tsx
- src/components/main/Expenses.tsx
- src/components/main/Goals.tsx
- src/components/main/Profit.tsx
- src/components/main/Revenue.tsx
- src/lib/authApi.ts
- 작업 번호: 173086074-F-GH
- main 페이지 loading 로직 개선 및 css 수정
- expenses 매출 페이지 추가
> Feat(expenses, main): 매출 페이지 추가, loading 페이지 개선, Desgin(main): css 변경

- package-lock.json
- src/app/expenses/page.tsx
- src/components/main/Expenses.tsx
- src/hooks/useReportQuery.tsx
- src/interface/report.ts
- src/lib/reportApi.ts
- 작업 번호: 173103714-F-GH
- 백엔드 확인하여 api 연결 진행
- 전달받는 type 추가
- 데이터 형식에 맞는 그래프 작동 방식 수정
> Refactor(expenses): api 연결

- src/app/expenses/page.tsx
- src/components/main/Expenses.tsx
- src/hooks/useExpensesQuery.tsx
- src/hooks/useReportQuery.tsx
- src/interface/expenses.ts
- src/interface/report.ts
- src/lib/expensesApi.ts
- src/lib/reportApi.ts
- 작업 번호: 173103714-F-GH
- api, hook, interface 를 매출(Expenses) 파일로 개별 분리
- 변경된 파일 경로 수정
> Remove(expenses): api, hook, interface 파일 분리, 경로 수정

- package-lock.json
- src/app/objective/page.tsx
- 작업 번호: 173102940-F-SJ
- 목표 설정 페이지
> feat(objective): 목표설정 페이지

- src/app/revenue/page.tsx
- 작업 번호: 173103420-F-HJ
- 매출 페이지 데이터 연결
> Feat(revenue):api 연결 완료

- src/Provider/QueryProvider.tsx
- src/app/goals/detail/page.tsx
- src/app/goals/page.tsx
- src/components/main/Revenue.tsx
- src/hooks/useRevenueQuery.tsx
- src/lib/revenueApi.ts
- 작업 번호: 
- 로그인 리다이렉트 로직 추가(변경예정) & 병합
> 로그인 리다이렉트 & 병합

- src/app/expenses/page.tsx
- src/components/expenses/ExpensesData.tsx
- src/components/expenses/ExpensesPieChart.tsx
- src/components/expenses/ExpensesWeekData.tsx
- src/interface/expenses.ts
- src/utils/calculateDay.ts
- 작업 번호: 173103714-F-GH
- 월별 매출 조회 페이지 로직 수정
- 주차별 매출 조회 기능 추가
> Feat(expenses): 주차별 조회 기능 추가

- src/app/goals/detail/page.tsx
- src/components/main/Goals.tsx
- src/utils/calculateDay.ts
> feat(goal-detail): api수정

- src/app/(withNav)/(goal)/goals/page.tsx
> feat(goal): 목표관리페이지 수정

- src/app/(withNav)/(goal)/goals/page.tsx
- 작업 번호: 
- api 수정 / 퍼센테이지 스타일 수정
> feat(goal): api 수정

- src/app/(withNav)/expenses/detail/page.tsx
- src/app/(withNav)/reportlist/detail/page.tsx
- src/app/(withNav)/reportlist/page.tsx
- src/components/expenses/ExpensesData.tsx
- src/components/expenses/ExpensesPieChart.tsx
- src/components/expenses/ExpensesWeekData.tsx
- src/components/reportlist/ReportItem.tsx
- src/hooks/useReportQuery.tsx
- src/interface/expenses.ts
- src/lib/reportApi.ts
- src/stores/useReportsStore.ts
- src/utils/calculateDay.ts
- 작업 번호: 173103714-F-GH
- expenses 상세 페이지 기능 수정
- report api 연결 로직 추가
> Feat(expenses, report): 기능 수정 및 추가

- src/app/(withNav)/mypage/page.tsx
> feat(mypage) : 마이페이지 수정

- src/app/(withNav)/reportlist/detail/page.tsx
> feat(reportlist-detail): 사업장이름 api연결

- src/app/(withNav)/revenue/page.tsx
- src/app/globals.css
- src/app/splash/page.tsx
- src/app/testCalendar/page.tsx
- src/components/Calendar.tsx
- src/components/Navbar.tsx
- src/interface/revenue.ts
- src/middleware.ts
- src/utils/currency.ts
> 캘린더 및 디자인 수정

- src/app/(withNav)/(goal)/goals/page.tsx
> feat(goal):지출예산 수정

- src/app/(withNav)/expenses/page.tsx
- src/components/reportlist/ReportItem.tsx
- 작업 번호: 
- ReportItem 컴포넌트 css 수정 (padding 이 active 시에만 적용되도록)
- expenses css 수정
> Desgin(expenses, report): css 수정

- Docker/Dockerfile
- nginx/default.conf
- src/app/(withNav)/(goal)/setGoals/page.tsx
- src/lib/authApi.ts
- src/lib/brApi.ts
- src/lib/expensesApi.ts
- src/lib/goalApi.ts
- src/lib/postApi.ts
- src/lib/profitApi.ts
- src/lib/reportApi.ts
- src/lib/revenueApi.ts
- src/lib/userApi.ts
- 작업 번호: 
- Fix(docker): 도커 관련 설정값 수정
> Fix(docker): 도커 관련 설정값 수정

- src/app/pos/page.tsx
- src/app/shop/page.tsx
> feat(pos,shop): pos/shop페이지 구현

- src/app/pos/page.tsx
- src/app/poslist/page.tsx
> feat(pos, poslist): 결제내역 페이지

- src/app/(withNav)/expenses/page.tsx
- src/components/reportlist/ReportIndusty.tsx
> TEST(jenkins): 자동화 테스트 3

- src/app/pos/page.tsx
- src/app/poslist/page.tsx
- src/hooks/useOrderQuery.tsx
- src/hooks/useProductQuery.tsx
- src/interface/product.ts
- src/lib/orderApi.ts
- src/lib/productApi.ts
- 작업 번호: 
- (pos-order/product): api 연결
> feat(pos-order/product): api 연결

- src/app/pos/page.tsx
- src/app/shop/page.tsx
- src/hooks/useShopQuery.tsx
- src/interface/product.ts
- src/interface/shop.ts
- src/lib/shopApi.ts
- 작업 번호: 
- shop: api 연결 / style수정
> feat(shop): api 연결

- src/app/shop/page.tsx
> shop 총합 수정

- src/app/(withNav)/card/page.tsx
- src/app/(withNav)/mpedit/page.tsx
- src/app/(withNav)/mypage/page.tsx
- 작업 번호: 
- card: 카드추천페이지 구현 / mypage,mpedit: 마이페이지 수정
> feat(card, mypage): 마이페이지 수정, 카드추천페이지 구현

- src/app/(withNav)/mypage/page.tsx
> feat(mypage): 로그아웃 수정

- src/app/(withNav)/(goal)/goals/page.tsx
- src/app/(withNav)/card/page.tsx
- src/app/(withNav)/expenses/page.tsx
- src/app/(withNav)/mypage/page.tsx
- src/components/Select.tsx
- src/hooks/useAuthQuery.tsx
- src/lib/authApi.ts
- 작업 번호: 
- 카드 추천 및 목표설정 css수정
> feat(card, goal): 카드 추천 및 목표설정 css수정

- src/app/(withNav)/card/page.tsx
> Design(card): css 수정

- src/lib/brApi.ts
> Fix(brApi):endpoint

- src/app/(withNav)/report/page.tsx
- src/components/expenses/ExpensesPieChart.tsx
- src/components/main/Expenses.tsx
- 작업 번호: 
- FIX(expense): 월별 지출 페이지 그래프 색상 오류 수정
> FIX(expense): 월별 지출 페이지 그래프 색상 오류 수정

- src/app/(withNav)/expenses/detail/page.tsx
- src/app/(withNav)/expenses/page.tsx
- src/components/expenses/ExpensesData.tsx
- src/components/expenses/ExpensesPieChart.tsx
- src/components/main/Expenses.tsx
- src/hooks/useCardQuery.tsx
- src/stores/useExpensesStore.ts
- 작업 번호: 
- FIX(expense): 금액 내림차순 설정, 카테고리-색상 매핑 삭제
> FIX(expense): 금액 내림차순 설정, 카테고리-색상 매핑 삭제

- src/app/(withNav)/expenses/detail/page.tsx
- src/app/(withNav)/expenses/page.tsx
- src/app/(withNav)/revenue/page.tsx
- 작업 번호: 
- (revenue, expenses):css수정 및 다음 달 이동 수정
> (revenue, expenses):css수정 및 다음 달 이동 수정

- package-lock.json
- package.json
- src/app/(auth)/newpassword/page.tsx
- src/components/FindPassword.tsx
- src/components/NewPassword.tsx
- src/hooks/useAuthQuery.tsx
- src/interface/resetPassword.ts
- src/lib/authApi.ts
- 작업 번호: 
- feat(password): find, new password
> feat(password): find, new password

- src/components/NewPassword.tsx
- src/lib/authApi.ts
> fix(password)

- src/components/NewPassword.tsx
- src/lib/authApi.ts
- 작업 번호: 
- fix(NewPassword): error message
> fix(NewPassword): error message

- src/app/(withNav)/mypage/page.tsx
- src/components/Login.tsx
> Fix(사업자 관련 에러)

- nginx/default.conf
> FIX(nginx): nginx 설정값 수정

- package-lock.json
- src/app/(auth)/newpassword/layout.tsx
> FEAT(newpssword): layout 페이지 추가

- src/app/(withNav)/report/detail/page.tsx
- src/components/Recommendation.tsx
- src/components/reportlist/ReportIndusty.tsx
- src/components/reportlist/ReportMarket.tsx
- 작업 번호: 
- Style(report): 디자인 수정
> Style(report): 디자인 수정

- package-lock.json
- src/components/Recommendation.tsx
> Fix(error):빌드에러 수정

- Docker/Dockerfile
> FIX(Dockerfile): 도메인 수정

- src/app/(auth)/login/page.tsx
- src/app/(auth)/register/page.tsx
- src/app/(auth)/validate/page.tsx
- src/app/(withNav)/mypage/page.tsx
- src/components/Login.tsx
- src/components/reportlist/ReportIndusty.tsx
- src/components/reportlist/ReportMarket.tsx
- src/hooks/useUserQuery.tsx
> Style(report): 리포트 수정

- src/app/(withNav)/card/page.tsx
- 작업 번호: 
- fix(card): card 이미지 수정
> fix(card): card 이미지 수정

- src/app/(withNav)/mypage/page.tsx
- 작업 번호: 
- feat(mypage): 내정보수정, 알림 숨기기
> feat(mypage): 수정

- src/app/(withNav)/(goal)/goals/detail/page.tsx
- src/app/(withNav)/(goal)/goals/page.tsx
- src/app/(withNav)/(goal)/setGoals/page.tsx
- src/app/(withNav)/card/page.tsx
- src/app/(withNav)/expenses/detail/page.tsx
- src/app/(withNav)/expenses/page.tsx
- src/app/(withNav)/page.tsx
- src/app/(withNav)/profit/page.tsx
- src/app/(withNav)/report/detail/page.tsx
- src/app/(withNav)/report/page.tsx
- src/app/(withNav)/revenue/page.tsx
- src/app/globals.css
- src/app/layout.tsx
- src/components/DynamicVh.tsx
- src/components/Login.tsx
- src/components/Select.tsx
- src/components/main/Expenses.tsx
- src/hooks/useUserQuery.tsx
- src/interface/error.ts
- src/lib/userApi.ts
- 작업 번호: 
- 메인에서 403 에러 발생 시 로그인 화면으로 redirect.
- safari에서 볼 때 화면 크기 수정
> Fix(403 error) & Style(safari env)

- src/app/health-check/page.tsx
> FEAT(health-check): 신규 페이지 추가

- src/app/health-check/page.tsx
> FIX(health-check): 페이지 수정

- src/app/health-check/page.tsx
> FIX(health-check): 헬스체크 수정

- src/app/health-check/page.tsx
> FIX(health-check): 경로 수정

- src/app/health-check/page.tsx
> FIX(health-check): 경로 오타 수정2

- src/app/health-check/page.tsx
- src/lib/authApi.ts
- src/lib/brApi.ts
- src/lib/cardApi.ts
- src/lib/expensesApi.ts
- src/lib/goalApi.ts
- src/lib/orderApi.ts
- src/lib/paymentApi.ts
- src/lib/postApi.ts
- src/lib/productApi.ts
- src/lib/profitApi.ts
- src/lib/reportApi.ts
- src/lib/revenueApi.ts
- src/lib/shopApi.ts
- src/lib/userApi.ts
> FIX(url): https 설정에 따라 백엔드 요청도 https로 변환

- src/app/health-check/page.tsx
- src/lib/authApi.ts
- src/lib/brApi.ts
- src/lib/cardApi.ts
- src/lib/expensesApi.ts
- src/lib/goalApi.ts
- src/lib/orderApi.ts
- src/lib/paymentApi.ts
- src/lib/postApi.ts
- src/lib/productApi.ts
- src/lib/profitApi.ts
- src/lib/reportApi.ts
- src/lib/revenueApi.ts
- src/lib/shopApi.ts
- src/lib/userApi.ts
> FIX(url): https->http 원상복구

- nginx/default.conf
> FIX(nginx): conf 파일 수정

- nginx/default.conf
> FIX(nginx): 세미콜론 누락 추가

- src/app/health-check/page.tsx
- src/lib/authApi.ts
- src/lib/brApi.ts
- src/lib/cardApi.ts
- src/lib/expensesApi.ts
- src/lib/goalApi.ts
- src/lib/orderApi.ts
- src/lib/paymentApi.ts
- src/lib/postApi.ts
- src/lib/productApi.ts
- src/lib/profitApi.ts
- src/lib/reportApi.ts
- src/lib/revenueApi.ts
- src/lib/shopApi.ts
- src/lib/userApi.ts
> FIX(url): 도메인 수정3

- src/lib/authApi.ts
- src/lib/brApi.ts
- src/lib/cardApi.ts
- src/lib/expensesApi.ts
- src/lib/goalApi.ts
- src/lib/orderApi.ts
- src/lib/paymentApi.ts
- src/lib/postApi.ts
- src/lib/productApi.ts
- src/lib/profitApi.ts
- src/lib/reportApi.ts
- src/lib/revenueApi.ts
- src/lib/shopApi.ts
- src/lib/userApi.ts
> FIX(url): 경로 수정 4

- src/app/(withNav)/profit/page.tsx
- src/interface/user.ts
- src/stores/useUserStore.ts
- 작업 번호: 
- feat(profit):report 경로 수정
> feat(profit):report 경로 수정

- src/app/health-check/page.tsx
> FIX(url): url 수정5

- src/lib/weather.ts
> FIX(weather): WEATHER_KEY 수정
